name: ci
on: [push]

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          ignore: DL3018
  server-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Lint & Test
        run: make setup-ci ci
  ui-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20.8
      - name: Lint & Test
        run: cd ui && npm ci && npm run ci
  docker:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [hadolint, server-test, ui-test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v4
      - name: Expose git context
        id: git
        run: |
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "ref=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.git.outputs.sha }}
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.git.outputs.ref }}
            ${{ env.REGISTRY }}/${{ github.repository }}:latest
          build-args: |
            GITHUB_SHA=${{steps.git.outputs.sha}}
            GITHUB_REF=${{steps.git.outputs.ref}}
          push: true
