name: release
on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v4
      - name: Expose git context
        id: git
        run: |
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "ref=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.git.outputs.sha }}
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.git.outputs.ref }}
            ${{ env.REGISTRY }}/${{ github.repository }}:latest
          build-args: |
            GITHUB_SHA=${{steps.git.outputs.sha}}
            GITHUB_REF=${{steps.git.outputs.ref}}
          push: true
